language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - lcov
      before_install:
        - eval "CC=gcc-4.8 && CXX=g++-4.8"
      script:
        - cmake -DENABLE_COVERAGE=ON ..
        - cmake --build . --config Debug
        - ctest . -C Debug
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - lcov
      script:
        - cmake -DENABLE_COVERAGE=ON ..
        - cmake --build . --config Debug #debug build needed for CodeCov
        - ctest . -C Debug
    #- os: windows
    #  script:
    #    - cmake ..
    #    - cmake --build .
    #    - ctest .

before_script:
  - mkdir build
  - cd build
  
after_success:
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    cd ${TRAVIS_BUILD_DIR};
    lcov --directory . --capture --output-file coverage.info;
    lcov --remove coverage.info '/usr/*' --output-file coverage.info;
    lcov --list coverage.info;
    bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports";
  fi
